name: gli3-sufu
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core dependencies
  - python=3.9
  - r-base=4.2
  - nextflow=22.10.6
  - mamba
  
  # Alignment tools
  - bowtie2=2.4.5
  - bwa=0.7.17
  - samtools=1.16
  - bedtools=2.30
  
  # Peak callers
  - macs2=2.2.7
  - seacr=1.3
  
  # Processing tools
  - deeptools=3.5
  - sra-tools=3.0
  - fastqc=0.11.9
  - multiqc=1.13
  - trimmomatic=0.39
  - picard=2.27
  
  # File format tools
  - ucsc-bedgraphtobigwig=377
  - ucsc-bigwigaverageoverbed=377
  
  # Annotation
  - homer=4.11
  
  # R packages
  - bioconductor-deseq2=1.36
  - bioconductor-diffbind=3.6
  - bioconductor-chipseeker=1.32
  - bioconductor-clusterProfiler=4.4
  - bioconductor-rtracklayer=1.56
  - bioconductor-genomicranges=1.48
  - bioconductor-bsgenome.mmusculus.ucsc.mm10=1.4
  - bioconductor-txdb.mmusculus.ucsc.mm10.knowngene=3.10
  - bioconductor-org.mm.eg.db=3.15
  - r-ggplot2=3.4
  - r-pheatmap=1.0
  - r-rcolorbrewer=1.1
  - r-ggrepel=0.9
  - r-dplyr=1.0
  - r-data.table=1.14
  
  # Python packages
  - pandas=1.5
  - numpy=1.24
  - scipy=1.10
  - matplotlib=3.6
  - seaborn=0.12
  - statsmodels=0.13
  - pyranges=0.0.120
  - genomepy=0.15
  
  # Development tools
  - pip
  - pip:
    - nf-core==2.7
